### PR TITLE
Expand R version support

### PR DESCRIPTION
**Pull request by okankcb**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by okankcb** [comment]
@conda-forge-admin please rerender

**Review by mfansler — CHANGES_REQUESTED** [review]
Generally, we don't want to have continued support outside of our current matrix (R 4.1 and 4.2). We could do this as a one time build to fill in legacy R version support, but *please provide some justification*. For example, explain why an R 4.1 or R 4.2 environment cannot be used?

In the future, it would be preferable to first request such things through an Issue and wait for maintainer feedback.

**Comment by okankcb** [comment]
> Generally, we don't want to have continued support outside of our current matrix (R 4.1 and 4.2). We could do this as a one time build to fill in legacy R version support, but _please provide some justification_. For example, explain why an R 4.1 or R 4.2 environment cannot be used?
> 
> In the future, it would be preferable to first request such things through an Issue and wait for maintainer feedback.

I appreciate your understanding on this matter. If installing only version 4.0 is indeed possible, it could sufficiently address our needs. The main reason for our request to support the legacy R version is due to dependencies on older packages and scripts that aren't fully compatible with R 4.1 or R 4.2. Updating these dependencies would demand considerable time and resources.

Furthermore, there might be users within our organization still using R 4.0 who haven't yet transitioned to the newer versions. Offering support for R 4.0 would enable them to maintain their existing environments without needing to upgrade, which could otherwise lead to disruptions in their workflow.

Moving forward, I'll ensure that the appropriate protocol is followed, and I'll submit such requests through an Issue, awaiting maintainer feedback.

Thank you in advance for your consideration and assistance in this matter.

**Comment by okankcb** [comment]
Additionally, the version 4.0 of R can be sufficient for several reasons:

- Backward compatibility: R has a good reputation for backward compatibility. Packages developed for previous versions of R are often compatible with newer versions. Therefore, if you have specific packages you want to use that are compatible with version 4.0, there may not be a need to use versions 4.1 or 4.2.

- Stability: New software versions can sometimes come with bugs or stability issues. By using an older version like 4.0, you can benefit from a version that has been tested and used for a longer period, reducing potential risks of technical issues.

- Package ecosystem: Most popular packages in the R ecosystem are compatible with version 4.0. These packages often provide extensive functionality and are regularly updated by their developers. Using version 4.0 allows you to access a wide range of packages without worrying about compatibility.

**Comment by mfansler** [comment]
Sounds good. There are some things I see need fixing in the recipe, so I will add some more edits before merging.

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Review by mfansler — APPROVED** [review]

**Review by mfansler — APPROVED** [review]

**Pull request merged**
